version: "3.9"

services:
  real_estate_next:
    container_name: real_estate_container
    image: real_estate_image
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env.development
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "3002:3002"
