version: "3.9"

services:
  real_estate_next:
    container_name: real_estate-container
    image: real_estate-image
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env.production
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "3002:3002"
